config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  root to: 'pages#home'

  get '/dashboard', to: 'pages#dashboard'
  get '/goals/:id/show_public', to: 'goals#show_public', as: 'show_public'
  # get 'goals/:goal_id/task/edit'
  resources :subjects, only: [:index, :show]
  resources :goals, only: [:index, :show, :new, :create, :edit, :update, :destroy,] do
    resources :tasks, only: [:create,:new,:show, :edit, :update, :index, :destroy]
  end

  post 'create_from_copy', to: 'goals#create_from_copy'

  post 'update_complete/:task_id', to: 'tasks#update_complete', as: "update_complete"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :subject
  belongs_to :user
  has_many :links
  has_many :tasks, dependent: :destroy

  #accepts_nested_attributes_for :tasks
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :goal
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :goals
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :goal
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :goals

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable #:confirmable --> requires new views
         # :trackable --> requires current_sign_in_a method
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if:  :devise_controller?

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end

  protected

    def configure_permitted_parameters

      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    end

    def after_sign_in_path_for(resource)
      request.env['omniauth.origin'] || stored_location_for(resource) || goals_path
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    if params[:difficulty]
      @goals = Goal.where(difficulty: params[:difficulty])
      @difficulty = params[:difficulty]
    elsif params[:query].present?
      sql_query = "name ILIKE?"
      @goals = Goal.where(sql_query, "%#{params[:query]}%")
    else
      @goals = Goal.all
    end
    @subject = Subject.all
    @tasktime = 0
    @new_goal = Goal.new

    respond_to do |format|
      format.html
      format.js
    end

    #should I go through all the tasks & calc --> total time, deadline?
  end

  def show
    @goal = Goal.find(params[:id])
    @tasks = Task.all
    @goals = Goal.all
    @links = Link.all

  end

  def show_public
    @goal = Goal.find(params[:id])
    @tasks = Task.all
    @goals = Goal.all
    @links = Link.all
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    @subject = Subject.find(params[:goal][:subject_id])
    @goal.subject = @subject

    if @goal.save
      redirect_to dashboard_path()
    else
      render 'new'
      # do
    end
  end

  def create_from_copy
    admin_goal = Goal.find(params[:id])
    @my_goal= admin_goal.dup
    @my_goal.votes = 1
    @my_goal.user = current_user

    if @my_goal.save
      admin_goal.tasks.each do |task|
        new_task = task.dup
        new_task.goal = @my_goal
        new_task.save
      end
      redirect_to goals_path()

    else
      render 'new'
      # do
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    @goal.update(goal_params)
    redirect_to goals_path(@goal)
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy()
    redirect_to dashboard_path()
  end

  private

  def goal_params
    params.require(:goal).permit(:name, :difficulty, :completed)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def dashboard
    @my_goals = current_user.goals
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    goals_path
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
     if params[:query].present?
       sql_query = "title ILIKE :query OR location ILIKE :query"
       @subjects = Subject.where(sql_query, query: "%#{params[:query]}%")
     else
       @subjects = Subject.all
     end
   end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
    @goal = Goal.find(params[:goal_id])
  end

  def create
    @task = Task.new(task_params)
    @goal = Goal.find(params[:goal_id])
    @task.goal = @goal
    if @task.save
      redirect_to goal_path(@goal)
    else
      render 'new'
      # do
    end
  end

  def edit
    @goal = Goal.find(params[:goal_id])
    @task = Task.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:goal_id])
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to goal_path(@goal)
  end

  def destroy
    @goal = Goal.find(params[:goal_id])
    @task = Task.find(params[:id])
    @task.destroy()
    redirect_to goal_path(@goal)
  end

  def update_complete
    task = Task.find(params[:task_id])
    task.completed = !task.completed
    @task_id = task.id
    @goal = task.goal

    if task.save
      @message = true
    else
      @message = task.errors.full_messages
    end

    respond_to do |format|
        format.html { redirect_to goal_path(@goal) }
        format.js
    end
  end


private

def task_params
  params.require(:task).permit(:name, :hours)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def calculate_time(goal)
    time = 0
    goal.tasks.each do |task|
      time += task.hours
    end

    return time
  end

  def first_deadline(goal)
    deadlines = []
    goal.tasks.each do |task|
        deadlines << task.deadline
    end
    return deadlines.sort[0]
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/goals/edit.html.erb
<div class="container ctn-login">
  <div class="login-top">
    <h3>Edita el curso (profesor)</h3>
  </div>
  <div class="login-box">
    <%= simple_form_for(@goal) do |f| %>
      <% if @goal.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @goal.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.input :name, placeholder: "What do you want to achieve?" %>
      <%#= f.input :subject, placeholder: "What subject it belongs to?"%>
      <%= f.association :subject, collection: Subject.all, promt: "What subject does it belong to?" %>
      <%= f.input :difficulty, collection: ["easy", "medium", "hard"] %>
      <%= f.input :description, placeholder: "Add a description to the goal" %>

      <div class="text-center">
        <%= f.submit "Done", class: "btn btn-primary" %>
      </div>
      <!-- [...] all the fields -->
    <% end %>

  </div>
</div>

app/views/goals/index.html.erb
<div class = "bg-grey">
  <div class="container ">
    <div class="row">
      <div class="col-xs-12">
        <h3 class="dashboard__h3 top-padding"> Elige entre las asignaturas y añade las favoritas </h3>
      </div>
      <div class="col-xs-12">
        <div class="search-form">
          <div class="search-rectangle">
            <%= form_tag goals_path, method: :get do %>
          </div>
            <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Qué quieres aprender hoy?" %>
        <% end %>
        </div>
        <h4 class="dashboard__h4 sm-padding">Selecciona la dificultad</h4>
        <div class="goal-index-filter">
          <div class="goal_index-filter__box" id="easy-parent">
            <%= link_to difficulty: "easy", remote: true do %>
            <!-- #remote: true -->
              <div class="goal-index-filter__green ">
              </div>
            <% end %>
          </div>

          <div class="goal_index-filter__box" id="medium-parent">
            <%= link_to difficulty: "medium", remote: true do %> <!-- #remote: true -->
              <div class="goal-index-filter__orange"></div>
            <% end %>
          </div>
          <div class="goal_index-filter__box" id="hard-parent">
            <%= link_to difficulty: "hard", remote: true do %> <!-- #remote: true -->
              <div class="goal-index-filter__red"></div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="dashboard__cards-wrapper sm-padding">
      <div class="row" id="row__card-holder">
        <%= render 'shared/goal-card' %>
      </div>
      <div class="col-xs-12">
        <div class=" dashboard__parent-btns text-center sm-padding">
          <%= link_to "DASHBOARD", dashboard_path, class: "btn btn-orange dashboard__btn-side-margin" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/goals/index.js.erb
 <%if @difficulty %>
  if ( typeof parentId === "undefined") {
    parentId = "<%= @difficulty %>-parent"
  } else {
    previousTrigger = document.querySelector(`#${parentId}`);
    previousTrigger.classList.toggle("goal-index-filter__active");
    parentId = "<%= @difficulty %>-parent"
  }
    trigger = document.querySelector(`#${parentId}`);
    trigger.classList.toggle("goal-index-filter__active");

  //TODO: Go back to showing everything once they click on disable filter (hard)

  if ( typeof cardContainer === "undefined") {
    cardContainer = document.querySelector ("#row__card-holder")
    console.log("its my first time")
    let original = cardContainer.innerHTML
    console.log(`${original}`)
  } else {
    cardContainer = document.querySelector ("#row__card-holder")
    console.log("its nth time")
  }
  cardContainer.innerHTML = "";
  var row = `<%= j render 'shared/goal-card' %>`
  cardContainer.insertAdjacentHTML("afterbegin", row )


 <%else %>
   console.log("You suck at coding")
 <%end %>


//   Add class to coloured circle that has the id of the difficulty
//   Clear the html from the row that holds the cards
//   Fill the row with the card html for each one

//  let card =  `
//  <div class="col-xs-12 col-sm-6">
//     <!-- if I link to do it fucks up the card -->
//         <div class="product card__border-orange">

//         <a class="product-link" href="/goals/1440/show_public">
//           <div class="product-upvote">
//             <div class="product-arrow"></div>
//             <div class="product-count">196</div>
//             <div class="product-downvote"></div>
//           </div>
//           <img class="product-image hidden-xs" src="/assets/others-284799cde2881adcd478b848cf0e513c85f72b3cdadce04e770e53c2a5d50e7b.svg">
//           <div class="product-body">
//             <h6>Average completion: 67 Hours</h6>
//             <h3>Try being a vegan</h3>
//             <p>OTHERS</p>
//           </div>
// </a>          <ul class="list-inline product-controls product-controls-hidden hidden-sm hidden-xs">
//             <li><a class="far fa-star" rel="nofollow" data-method="post" href="/create_from_copy?id=1440">Add</a></li>
//           </ul>
//       </div>
//   </div>`

//<% @goals.sort_by { |goal| goal.difficulty } %>

app/views/goals/new.html.erb
<div class="login__wrapper" style="background-image: url('<%= image_path('Sign-up.png') %>')">
  <div class="container ctn-login">
    <div class="login-top">
      <h3>Crea tu asignatura</h3>
    </div>
    <div class="goal-new__box">
      <%= simple_form_for(@goal) do |f| %>
        <% if @goal.errors.any? %>
          <div class="errors-container">
            <ul>
              <% @goal.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.input :name, placeholder: "De qué se trata?" %>
        <%#= f.input :subject, placeholder: "What subject it belongs to?"%>
        <%= f.association :subject, collection: Subject.all, promt: "A qué area pertenece?" %>
        <%= f.input :difficulty, collection: ["easy", "medium", "hard"]%>
        <%= f.input :description, placeholder: "Añade una descripción a tu assignatura" %>

        <div class="text-center">
          <%= f.submit "Done", class: "btn btn-homepage xs-margin" %>
        </div>
        <!-- [...] all the fields -->
      <% end %>

    </div>
  </div>
</div>

app/views/goals/show.html.erb
<div class="goal-show__wrapper">
  <div class="goal-show__top-content">
    <div class="goal-show__goal-word">
    Gestiona tus asignaturas e interactua con su contenido
    </div>
    <div class="goal-show__goal-title">
    <%= @goal.name %>
    </div>
    <div class="add-task-btn">
     <%= link_to "Add task", new_goal_task_path(@goal), class: "add-task-btn2" %>
    </div>
  </div>
   <div class="task-card__row">
      <% @goal.tasks.each_with_index do |task, index| %>
         <div class="task-card  <%= task.completed ? 'active' : '' %>" id="taskId<%= task.id %>">
          <div class="task-card-left">
            <!--  -->
                <%= link_to update_complete_path(task), method: "post", remote: true do %>
                  <%= image_tag "check.svg", class:'task-card-check' %>
                  <%= image_tag "check-white.svg", class:'task-card-check-white' %>
                <% end %>
                <%= link_to image_tag("edit.svg"), edit_goal_task_path(@goal, task), class:"task-card-edit"  %>
                <%= link_to image_tag("edit-white.svg"), edit_goal_task_path(@goal, task), class:"task-card-edit-white"  %>
                <h2 class="task-card-taskname"><%= task.name %>
                </h2>
             </div>
             <%= link_to image_tag("delete-white.svg"), goal_task_path(@goal, task), method: "delete",class:"task-card-delete-white" %>
             <%= link_to image_tag("delete.svg"), goal_task_path(@goal, task), method: "delete",class:"task-card-delete" %>
        </div>
      <% end %>
      <div class="link-container">
        <div class="youtube-container">
          <div class="youtube-card">
            <div class="youtube-front">
              <i class="fab fa-youtube"></i>
            </div>
            <div class="youtube-back">
              <%= @links.last.name %>
            </div>
          </div>
        </div>
        <div class="drive-container">
          <div class="drive-card">
            <div class="drive-front">
              <i class="fab fa-google-drive"></i>
            </div>
            <div class="drive-back">
              <%= @links.last.name %>
            </div>
          </div>
        </div>
        <div class="drop-container">
          <div class="drop-card">
            <div class="drop-front">
              <i class="fab fa-dropbox">
              </i>
            </div>
            <div class="drop-back">
              <%= @links.last.name %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/goals/show_public.html.erb
<div class="goal-show__wrapper">
  <div class="goal-show__top-content">
    <div class="goal-show__goal-word">
    Goal
    </div>
    <div class="goal-show__goal-title">
    <%= @goal.name %>
    </div>
    <div class="add-task-btn">
     <%#= link_to "Add task", new_goal_task_path(@goal), class: "add-task-btn2" %>
      <%= link_to "Import Goal", create_from_copy_path(id: @goal.id), method: "post", class: "add-task-btn2" %>
    </div>
  </div>
   <div class="task-card__row">
      <% @goal.tasks.each_with_index do |task, index| %>
         <div class="task-card">
          <div class="task-card-left">
            <!--  -->
                <h2 class="task-card-taskname">
                  <%= task.name %>
                </h2>
             </div>
        </div>
      <% end %>
      <div class="link-container">
        <div class="youtube-container">
          <div class="youtube-card">
            <div class="youtube-front">
              <i class="fab fa-youtube"></i>
            </div>
            <div class="youtube-back">
              <%= @links.last.name %>
            </div>
          </div>
        </div>
        <div class="drive-container">
          <div class="drive-card">
            <div class="drive-front">
              <i class="fab fa-google-drive"></i>
            </div>
            <div class="drive-back">
              <%= @links.last.name %>
            </div>
          </div>
        </div>
        <div class="drop-container">
          <div class="drop-card">
            <div class="drop-front">
              <i class="fab fa-dropbox">
              </i>
            </div>
            <div class="drop-back">
              <%= @links.last.name %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<% solid_nav = true %>
<% if current_page?(root_path) %>
    <% solid_nav = false %>
<% end %>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= favicon_link_tag 'favicon-white.png' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <style> @import url('https://fonts.googleapis.com/css?family=Montserrat:300'); </style>
  </head>
  <body>
    <div class="pages-container <%= solid_nav ? 'solid-nav' : '' %> ">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="dashboard-container">
    <div class="dashboard-row">
      <div class="dashboard-top-text">
        <div class="dashboard__h3 text-center ">
          Gestiona tus asignaturas
        </div>
      </div>
      <div class="dashboard-links">
        <%= link_to "Sugiere una nueva asignatura", new_goal_path, class: "btn btn-orange dashboard__btn-side-margin" %>
      </div>
      <div class="dashboard__cards-wrapper lg-padding">
        <div class="row">
          <% if current_user.goals.any? %>
            <%= render 'shared/my-goal-card' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
 <div class="homepage" style="background-image: url('<%= image_path 'learnbox-background.png' %>')">
    <%= render 'shared/home-banner' %>
    <div class="container">
      <div class="features-card__wrapper">
          <h1 class="simple__heading">ES MUY SIMPLE: </h1>
          <p class="simple__text features-card__text">Consigue adentrarte en nuevas áreas de conocimiento. Los cursos desglosan  conceptos complejos cómo la Inteligencia Artificial en pequeños pasos. Cuantifica tu progreso y recibe apoyo de nuestro grupo de profesores expertos. Al completar el curso, si estás realizando un grado, recibirás 3 Créditos ECTS de tus asignaturás de libre elección. </p>
          <div class="features-card-container">

            <div class="features-card">
              <div class="features-card-image">
               <%= image_tag "goal.svg" %>
              </div>
              <div class="features-card-content">
                <div class="features__text-l">Elige tu foco</div>
                <div class="features__text-m">Hay asignaturas opt. y experimentales</div>
                <div class="features__text-s">Estas asignaturas han sido co-creadas junto a las empresas líderes del sector junto con estudiantes de grado. Estamos aquí para ayudarte.</div>
              </div>
            </div>

            <div class="features-card">
              <div class="features-card-image">
                <%= image_tag "contract.svg" %>
              </div>
              <div class="features-card-content">
                <div class="features__text-l">Organizate</div>
                <div class="features__text-m">Generaremos un plan para ayudarte</div>
                <div class="features__text-s">Acaba la asignatura sin imprevistos. Aprende hábitos de estudio que te ayudaran con las otras asignaturas y en tu futuro profesional</div>
              </div>
            </div>
            <div class="features-card">
              <div class="features-card-image">
                <%= image_tag "start.svg" %>
              </div>
              <div class="features-card-content">
                <div class="features__text-l">Ponlo en práctica</div>
                <div class="features__text-m">Haz tus proyectos realidad</div>
                <div class="features__text-s">Resultados reales para prácticas reales. Consigue tu próximo empleo mientras estudias. </div>
              </div>
            </div>
          </div>
      </div>
    </div>

    <div class="container pricing__wrapper">
      <h1 class="simple__heading"> Inscríbete ya </h1>
      <p class="pricing__text"> Formación excepcional a un precio asequible.</p>
      <%= render 'shared/pricing' %>
    </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">

    <a href="https://github.com/jcllobet/learning_platform"><i class="fa fa-github"></i></a>
    <a href="https://www.instagram.com/cocacola/"><i class="fa fa-instagram"></i></a>

    <a href="https://www.facebook.com/pages/Coca-Cola-Espa%C3%B1a/1393245584230208"><i class="fa fa-facebook"></i></a>

    <a href="https://twitter.com/cocacolaco_es/status/1052827190851715073"><i class="fa fa-twitter"></i></a>

    <a href="https://www.linkedin.com/company/the-coca-cola-company/"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  </div>
</div>

app/views/shared/_goal-card.html.erb
<% @goals = @goals.sort_by { |goal| goal.votes} %>
<% @goals.reverse! %>
<% @goals.each do |goal| %>
  <div class="col-xs-12 col-sm-6">
    <!-- if I link to do it fucks up the card -->
      <% if goal.difficulty == "hard" %>
        <div class="product card__border-hard">

      <% elsif goal.difficulty == "medium" %>
        <div class="product card__border-medium">

      <% else %>
        <div class="product card__border-easy">
      <% end %>
        <%= link_to show_public_path(goal), class: "product-link" do %>
          <div class='product-upvote'>
            <div class="product-arrow"></div>
            <div class='product-count'><%= goal.votes %></div>
            <div class="product-downvote"></div>
          </div>
          <%= image_tag goal.subject.name.downcase + '.svg', class: "product-image hidden-xs"%>
          <div class='product-body'>
            <h6>Tiempo estimado: <%= calculate_time(goal) %> Horas</h6>
            <h3><%= goal.name %></h3>
            <p><%= goal.subject.name.upcase %></p>
          </div>
        <% end %>
          <ul class="list-inline product-controls product-controls-hidden hidden-sm hidden-xs">
            <li><%= link_to "Add", create_from_copy_path(id: goal.id), method: "post", class: "far fa-star" %></li>
          </ul>
      </div>
  </div>
<% end %>

app/views/shared/_my-goal-card.html.erb
<% current_user.goals.each do |goal| %>
  <!-- doing displaying a different card according to if there's a next item or not -->
  <div class="col-xs-8 col-xs-offset-2">
    <% if goal.difficulty == "hard" %>
      <div class="product card__border-hard">
    <% elsif goal.difficulty == "medium" %>
      <div class="product card__border-medium">
    <% else %>
      <div class="product card__border-easy">
    <% end %>
      <%= link_to goal_path(goal), class: "product-link" do %>
        <div class='product-upvote'>
          <div class="product-arrow"></div>
          <div class='product-count'><%= goal.votes %></div>
          <div class="product-downvote"></div>
        </div>
        <%= image_tag goal.subject.name.downcase + '.svg', class: "product-image hidden-xs"%>
        <div class='product-body'>
          <h6>Tiempo estimado: <%= calculate_time(goal) %> Horas</h6>
          <h3><%= goal.name %></h3>
          <p><%= goal.subject.name.upcase %></p>
        </div>
        <div class='product-task'>
          <% counter = 0 %>
          <% goal.tasks.each do |task| %>
            <% if task.completed %>
              <% counter += 1 %>
            <% end %>
          <%end %>
          <%= "#{counter} / #{goal.tasks.length}" %>
        </div>
      <% end %>
        <ul class="list-inline product-controls product-controls-hidden hidden-sm hidden-xs">
          <li><%= link_to "", edit_goal_path(goal), class: "fa fa-edit" %></li>
          <li><%= link_to "", goal_path(goal), method: "delete", class: "far fa-trash-alt" %></li>
        </ul>
      </div>
  </div>
<% end %>

app/views/subjects/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
      <h1>Mind Blowing courses</h1>
    </div>
  </div>
  <div class="row">
    <% @subjects.each_with_index do |subject, index| %>
      <div class="col-xs-12 col-md-4 col-lg-3">
        <%= link_to subject_path(subject) do  %>
        <div class="subject-card">
          <div class="subject-card-image" style='background-image: url("https://source.unsplash.com/random/<%=(index+15)*10 %>")'></div>
          <div class="subject-card-content">
            <div class="subject-card-title">
              <h4><%= subject.name %></h4>
            </div>
            <p><%= subject.description %></p>
            <p><i class="fas fa-utensils"></i>  <%= subject.subject_difficulty %></p>
            <div class="flex">
              <div class="card__conent-align-left">
                <i class="fas fa-users"> </i><span><%= subject.rating%></span>
              </div>
              <div class="card__conent-align-right">
                <i class="fas fa-euro-sign"> </i> <%= subject.subject_progress%>
              </div>
            </div>
          </div>
        </div>
        <%end%>
      </div>
    <% end %>
  </div>
</div>